version: 0.2

phases:
  install:
    commands:
      - echo Installing rclone...
      - curl https://rclone.org/install.sh | sudo bash
      - rclone --version
      - echo Configuring rclone for Wasabi and S3 using IAM roles...
      - |
        rclone config create wasabi s3 \
        env_auth=false \
        access_key_id=$WASABI_ACCESS_KEY \
        secret_access_key=$WASABI_SECRET_KEY \
        endpoint=$WASABI_ENDPOINT \
        region=$WASABI_REGION \
        acl=private \
        provider=Wasabi
      - |
        rclone config create s3 s3 \
          env_auth=true \
          region=$AWS_REGION \
          provider=AWS

  build:
    commands:
      - echo Starting dry run for migration from Wasabi to S3...
      - |
        if rclone copy --dry-run --files-from copylist.txt wasabi:duplitech-samsung/poc/ s3:wasabi-to-s3-automated-data-transfer-logs/wasabi-files/ --progress -vv; then
          echo "Dry run completed successfully."
        else
          echo "Dry run failed." >&2
          exit 1
        fi
      - echo "Dry run successful. Proceeding with actual migration..."
        
      - TIMESTAMP=$(date +%Y-%m-%d_%H-%M-%S)
      - LOG_FILE="transfer-log-${TIMESTAMP}.txt"
      
      - |
        RETRY_COUNT=0
        MAX_RETRIES=2
        STATUS="failure"
        while [ $RETRY_COUNT -le $MAX_RETRIES ]; do
          if rclone copy --files-from copylist.txt wasabi:duplitech-samsung/poc/ s3:wasabi-to-s3-automated-data-transfer-logs/wasabi-files/ -vv --log-file $LOG_FILE; then
            echo "Migration completed successfully."
            STATUS="success"
            ERROR_MESSAGE=""
            break
          else
            echo "Migration attempt $((RETRY_COUNT + 1)) failed." >&2
            RETRY_COUNT=$((RETRY_COUNT + 1))
            STATUS="failure"
            ERROR_MESSAGE="Failed after $RETRIES attempt(s)"
            sleep 10 # Wait before retrying
          fi
        done

        if [ "$STATUS" = "failure" ]; then
          echo "Uploading log file to S3..."
          echo $ERROR_MESSAGE
          aws s3 cp $LOG_FILE s3://wasabi-to-s3-automated-data-transfer-logs/transfer-logs/
          exit 1
        fi


      - echo "Uploading log file to S3..."
      - aws s3 cp $LOG_FILE s3://wasabi-to-s3-automated-data-transfer-logs/transfer-logs/

artifacts:
  files:
    - copylist.txt
    - "**/*.txt"
